# Generated by Django 6.0 on 2026-09-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bid_estimated_time_bid_message_bid_quick_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='id_proof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
