# Generated by Django 6.1 on 2026-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
