# Generated by Django 6.0 on 2026-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='bid_attachments/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='proposal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
