# Generated by Django 6.0 on 2026-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bid_attachment_bid_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='employee_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('company', 'Company Vendor')], default='vendor', max_length=20),
        ),
    ]
