# Generated by Django 6.1.1 on 2026-09-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Infinity Ventures', max_length=255)),
                ('contact_email', models.EmailField(default='support@infinityventures.com', max_length=254)),
                ('support_phone', models.CharField(default='+91 0000000000', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
