# Generated by Django 6.1.1 on 2026-09-23 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_globalsettings_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category_name', models.CharField(default='Renovation', max_length=100)),
                ('budget_range', models.CharField(default='₹45,000 - ₹60,000', max_length=100)),
                ('location', models.CharField(default='Ranchi, Jharkhand', max_length=100)),
                ('timeline', models.CharField(default='30 Days', max_length=100)),
                ('vendor_quote_preview', models.CharField(default='Lowest bid: ₹42,500 · 3 Verified Contractors quoted', max_length=255)),
                ('bids_count', models.IntegerField(default=5)),
                ('status_tag', models.CharField(default='Active Bidding', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/featured_projects/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='DUAL-ENGINE MARKETPLACE', max_length=100)),
                ('headline', models.CharField(default='Book instant home pros or get competitive bids for custom projects.', max_length=255)),
                ('subtext', models.TextField(default="India's smartest service network. Book verified technicians at upfront prices in 60 seconds, or post major contracting jobs and compare bids side-by-side.")),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='cms/hero/')),
                ('cta_primary_text', models.CharField(default='Post a Quick Service', max_length=100)),
                ('cta_primary_url', models.CharField(default='/user/quick-services/create.html', max_length=255)),
                ('cta_secondary_text', models.CharField(default='Post a Custom Job', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/user/jobs/create.html', max_length=255)),
                ('stat1_number', models.CharField(default='60s', max_length=50)),
                ('stat1_label', models.CharField(default='Instant Pro Matching', max_length=100)),
                ('stat2_number', models.CharField(default='15k+', max_length=50)),
                ('stat2_label', models.CharField(default='Verified Technicians', max_length=100)),
                ('stat3_number', models.CharField(default='100%', max_length=50)),
                ('stat3_label', models.CharField(default='Price Protection', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='PackageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('price_unit', models.CharField(default='/ Project', max_length=50)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('feature_bullets', models.TextField(default='Complete deep inspection\nStandard warranty included\nVerified background-checked pros', help_text='Enter features separated by newlines')),
                ('filter_tag', models.CharField(default='All', help_text='e.g. All, Plumbing, Electrical, Cleaning', max_length=50)),
                ('cta_label', models.CharField(default='Book Package', max_length=100)),
                ('cta_url', models.CharField(default='/user/quick-services/create.html', max_length=255)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/quick_services/')),
                ('price', models.DecimalField(decimal_places=2, default=299.0, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(default='45 Mins', max_length=100)),
                ('category_tag', models.CharField(default='Plumbing', max_length=100)),
                ('badge_text', models.CharField(blank=True, default='Instant', max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Infinity Ventures', max_length=255)),
                ('tagline', models.CharField(default='Instant Home Services & Custom Project Bidding Marketplace', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('contact_email', models.EmailField(default='support@infinityventures.com', max_length=254)),
                ('support_phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('address', models.CharField(default='Main Road, Ranchi, Jharkhand, India', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com', null=True)),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', null=True)),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com', null=True)),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com', null=True)),
                ('copyright_text', models.CharField(default='© 2026 Infinity Ventures. All rights reserved.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Branding',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_role_or_company', models.CharField(default='Homeowner, Ranchi', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='cms/testimonials/')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_text', models.TextField(default='Amazing experience! The technician arrived in under 30 minutes and resolved our electrical issue with full transparent pricing.')),
                ('service_taken', models.CharField(default='Emergency Electrical Repair', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa-solid fa-shield-halved', help_text='FontAwesome icon class', max_length=100)),
                ('stat_number', models.CharField(default='100%', max_length=50)),
                ('label', models.CharField(default='Verified & Background Checked', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
