# Generated by Django 6.1.1 on 2026-09-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_featuredprojectcard_herosection_packagecard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_city',
            field=models.CharField(blank=True, help_text='Assigned City (optional) for Area Admin', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_state',
            field=models.CharField(blank=True, help_text='Assigned State/Territory for Area Admin', max_length=100, null=True),
        ),
    ]
