# Generated by Django 6.1.1 on 2026-09-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_customuser_assigned_city_customuser_assigned_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='max_bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed bid price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_bids',
            field=models.IntegerField(blank=True, default=10, help_text='Maximum allowed bids', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed bid price', max_digits=10, null=True),
        ),
    ]
