# Generated by Django 6.1.1 on 2026-09-24 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_job_assigned_vendor_job_max_bid_amount_job_max_bids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID')], max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('id_document_front', models.FileField(upload_to='kyc/id_docs/')),
                ('id_document_back', models.FileField(blank=True, null=True, upload_to='kyc/id_docs/')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='kyc/licenses/')),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='kyc/gst/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Verified & Approved'), ('rejected', 'Rejected / Re-upload Required')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
