# Generated by Django 6.1.1 on 2026-09-25 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_payoutrequest_vendorwallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='contact_email',
            field=models.EmailField(default='support@sugguservices.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='site_title',
            field=models.CharField(default='Suggu Services', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='contact_email',
            field=models.EmailField(default='support@sugguservices.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='copyright_text',
            field=models.CharField(default='© 2026 Suggu Services. All rights reserved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='site_title',
            field=models.CharField(default='Suggu Services', max_length=255),
        ),
        migrations.CreateModel(
            name='DisputeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('payment', 'Payment / Pricing Issue'), ('quality', 'Poor Work Quality / Incomplete'), ('noshow', 'No Show / Unreachable'), ('behavior', 'Misbehavior / Unprofessional Conduct'), ('delay', 'Delay in Execution / Missed Deadline'), ('platform', 'Platform or Account Issue'), ('other', 'Other Issue')], default='quality', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_image', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent — Safety Concern')], default='medium', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('against_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_disputes', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='myapp.job')),
                ('quick_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='myapp.quickservice')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Ticket',
                'verbose_name_plural': 'Dispute Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.disputeticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
