# Generated by Django 6.1.1 on 2026-09-25 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_globalsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCompletionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='jobs/proof/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='jobs/proof/')),
                ('work_summary', models.TextField()),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_proof', to='myapp.job')),
                ('quick_service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_proof', to='myapp.quickservice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_completion_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Completion Proof',
                'verbose_name_plural': 'Job Completion Proofs',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_title', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField()),
                ('review_image', models.ImageField(blank=True, null=True, upload_to='reviews/photos/')),
                ('status', models.CharField(choices=[('published', 'Published'), ('pending', 'Under Review'), ('hidden', 'Hidden')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='myapp.job')),
                ('quick_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='myapp.quickservice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Review',
                'verbose_name_plural': 'Service Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
