# Generated by Django 6.1.1 on 2026-09-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_jobcompletionproof_servicereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustmetric',
            name='badge_text',
            field=models.CharField(blank=True, help_text='e.g. 100% of active pros verified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trustmetric',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed trust point description', null=True),
        ),
        migrations.AddField(
            model_name='trustmetric',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG markup for icon', null=True),
        ),
        migrations.AddField(
            model_name='trustmetric',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Aadhaar & Police Verified', max_length=255, null=True),
        ),
    ]
