# Generated by Django 6.1.1 on 2026-09-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
