# Generated by Django 6.1.1 on 2026-09-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_delete_complaint_vendorprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='available_bids',
            field=models.IntegerField(default=5),
        ),
    ]
