# Generated by Django 6.1.1 on 2026-09-30 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_vendorprofile_available_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='quick_service',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='additional_requirements',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='bids_count',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='contact_mobile',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='required_work',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='shift_availability',
        ),
        migrations.RemoveField(
            model_name='quickservice',
            name='user',
        ),
        migrations.AddField(
            model_name='quickservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='service_packages',
            field=models.JSONField(blank=True, default=list, help_text="List of packages/variants e.g. [{'name': 'Haircut', 'price': 150}]", null=True),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quickservice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('service_address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('quick_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='myapp.quickservice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
