# Generated by Django 6.1.1 on 2026-09-30 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_bid_quick_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='quick_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_bids', to='myapp.quickservice'),
        ),
    ]
