# Generated by Django 6.1.1 on 2026-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_bid_quick_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickservice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vendor service latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='locality',
            field=models.CharField(blank=True, help_text='Colony/Locality name e.g. Lalpur, Doranda', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vendor service longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='service_radius_km',
            field=models.FloatField(default=10.0, help_text='Maximum service radius in km (default 10km)'),
        ),
    ]
