# Generated by Django 6.1.1 on 2026-09-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_quickservice_latitude_quickservice_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Job location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='locality',
            field=models.CharField(blank=True, help_text='Colony/Locality name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Job location longitude', max_digits=9, null=True),
        ),
    ]
