# Generated by Django 6.1.1 on 2026-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_job_latitude_job_locality_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickservice',
            name='exclusions',
            field=models.JSONField(blank=True, default=list, help_text='List of exclusions', null=True),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quick_services/'),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='image_url',
            field=models.CharField(blank=True, help_text='Direct or preset image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quickservice',
            name='inclusions',
            field=models.JSONField(blank=True, default=list, help_text='List of inclusions', null=True),
        ),
    ]
