# Generated by Django 6.1.1 on 2026-09-30 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_quickservice_exclusions_quickservice_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='credits_added',
            field=models.IntegerField(default=15, help_text='Number of bid credits added with this package'),
        ),
        migrations.CreateModel(
            name='BidCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchased', 'Credits Purchased'), ('used', 'Bid Placed'), ('refund', 'Credit Refund'), ('bonus', 'Welcome / Bonus Credits')], max_length=20)),
                ('credits', models.IntegerField(help_text='Positive for additions (+15), negative for usage (-1)')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.job')),
                ('related_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.subscription')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
