# Generated by Django 6.1.1 on 2026-10-01 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_subscription_credits_added_bidcredittransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan Name e.g. Starter Pack, Value Pack, Pro Contractor', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='Short subtitle e.g. For occasional bidding', max_length=255, null=True)),
                ('credits', models.PositiveIntegerField(help_text='Number of bids / credits provided (e.g. 5, 10, 30)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (e.g. 100.00, 200.00, 500.00)', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for strikethrough comparison', max_digits=10, null=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight with Most Popular / Best Value badge')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this plan for vendors')),
                ('order', models.IntegerField(default=0, help_text='Display sort order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Bid Plan',
                'verbose_name_plural': 'Bid Plans',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='free_starter_bids',
            field=models.IntegerField(default=5, help_text='Free starter bids given to newly registered vendors'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='min_bids_per_job',
            field=models.IntegerField(default=1, help_text='Bids deducted per job quotation proposal'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='single_bid_cost',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Cost of a single bid credit in INR', max_digits=8),
        ),
    ]
