# Generated by Django 6.1.1 on 2026-10-01 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_bidplan_globalsettings_free_starter_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='CGST collected in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='cgst_percent_applied',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='CGST % applied', max_digits=5),
        ),
        migrations.AddField(
            model_name='bid',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission fee in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='commission_percent_applied',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission % at bid time', max_digits=5),
        ),
        migrations.AddField(
            model_name='bid',
            name='flat_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat convenience fee in INR', max_digits=8),
        ),
        migrations.AddField(
            model_name='bid',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='SGST collected in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='sgst_percent_applied',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='SGST % applied', max_digits=5),
        ),
        migrations.AddField(
            model_name='bid',
            name='total_customer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final payable amount charged to customer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='vendor_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net amount vendor receives upon completion', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Central GST % applied on platform commission', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='platform_flat_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed convenience / platform flat fee in INR', max_digits=8),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sgst_percent',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='State GST % applied on platform commission', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tax_calculation_mode',
            field=models.CharField(choices=[('commission_only', 'Tax on Platform Fee Only'), ('total_invoice', 'Tax on Total Service Invoice')], default='commission_only', help_text='Choose whether GST applies to platform commission or total customer invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission cut %', max_digits=5),
        ),
        migrations.CreateModel(
            name='PlatformRevenueLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_payout', models.DecimalField(decimal_places=2, help_text='Net amount credited to vendor wallet', max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, help_text='Platform commission earned', max_digits=10)),
                ('cgst_collected', models.DecimalField(decimal_places=2, default=0.0, help_text='Central GST collected', max_digits=10)),
                ('sgst_collected', models.DecimalField(decimal_places=2, default=0.0, help_text='State GST collected', max_digits=10)),
                ('flat_fee_collected', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat fee collected', max_digits=8)),
                ('total_customer_paid', models.DecimalField(decimal_places=2, help_text='Total amount paid by customer', max_digits=10)),
                ('settled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_ledgers', to='myapp.bid')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.job')),
                ('related_quick_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.quickservice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settled_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Revenue Ledger',
                'verbose_name_plural': 'Platform Revenue Ledgers',
                'ordering': ['-settled_at'],
            },
        ),
    ]
