# Generated by Django 6.1.1 on 2026-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_bid_cgst_amount_bid_cgst_percent_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='contact_email',
            field=models.EmailField(default='support@sugu.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='site_title',
            field=models.CharField(default='Sugu', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='contact_email',
            field=models.EmailField(default='support@sugu.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='copyright_text',
            field=models.CharField(default='© 2026 Sugu. All rights reserved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='site_title',
            field=models.CharField(default='Sugu', max_length=255),
        ),
    ]
