# Generated by Django 6.1.1 on 2026-10-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='qs_cgst_percent',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Quick Services Central GST %', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qs_commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Quick Services Platform Commission Cut %', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qs_flat_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quick Services Platform Flat Fee in INR', max_digits=8),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qs_sgst_percent',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Quick Services State GST %', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qs_tax_mode',
            field=models.CharField(choices=[('commission_only', 'Tax on Platform Cut Only'), ('total_invoice', 'Tax on Total Service Price')], default='commission_only', help_text='Choose whether GST applies to platform cut only or full service price for Quick Services', max_length=20),
        ),
    ]
