# Generated by Django 6.1.1 on 2026-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, help_text='Job city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, help_text='Job state', max_length=100, null=True),
        ),
    ]
