# Generated by Django 6.1.1 on 2026-10-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_globalsettings_qs_cgst_percent_and_more'),
        ('myapp', '0040_job_city_job_state'),
    ]

    operations = [
    ]
