# Generated by Django 6.1.1 on 2026-10-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_merge_20261003_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrevenueledger',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_ledgers', to='myapp.servicebooking'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
