# Generated by Django 6.1.1 on 2026-10-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_merge_20261005_0916'),
        ('myapp', '0042_platformrevenueledger_related_booking_and_more'),
    ]

    operations = [
    ]
