# Generated by Django 6.1.1 on 2026-10-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_merge_20261005_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='myapp.servicebooking'),
        ),
    ]
