# Generated by Django 6.1.1 on 2026-10-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_servicereview_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_online',
            field=models.BooleanField(default=True, help_text='Is vendor currently accepting bookings?'),
        ),
    ]
