# Generated by Django 6.1.1 on 2026-10-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_categoryfield_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryField',
        ),
    ]
