# Generated by Django 6.1.1 on 2026-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_delete_categoryfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='category',
            field=models.CharField(default='General', max_length=500),
        ),
    ]
