# Generated by Django 6.1.1 on 2026-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_alter_vendorprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, help_text='Job site photo or reference image', null=True, upload_to='jobs/'),
        ),
    ]
