# Generated by Django 6.1.1 on 2026-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_jobimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(blank=True, help_text='Operating city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vendor location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vendor location longitude', max_digits=9, null=True),
        ),
    ]
